### ISSUE TITLE
Dropping python 2.x support (tag  2.x compatible version?)

### ISSUE THREAD

**Issue by autoferrit** [plaid/plaid-python#102]
I am curious to your opinion on dropping python 2.x support in this library. As it stands, python 2 will be End of Life on PyCon 2020. And python 3 usage has surpassed 2.x usage. Most libraries (and now django 2.0) is dropping support for python 2 and supporting 3.4+ (my preference is for 3.5+ for type annotations).

As in another issue I posted about adding async support, I would like to use more modern language features. Not supporting python 2.x will make that much easier. 

I know some people are probably using this with 2.x, so I expect some resistance with this. It is fine. I am still debating whether I want to make a dedicated async only fork of plaid-python, which would be easiest. Or to make a PR to this repo to add support for async but still need to keep python 2.x support.

This is why I have these 2 issues. I am willing to do much of the work for this. As otherwise, I will be forking it anyways.

**Comment by joyzheng** [comment]
Apologies for the long delay in replying here, and thanks for bringing this up.

Since we have a few years until Python 2 EOL, you're right that it's probably too early for us to drop python 2.x support yet given existing users. However, we'd definitely appreciate PRs which make it possible to use newer features so long as the library remains python2 compatible.
