### ISSUE TITLE
suppress_warnings flag clarification

### ISSUE THREAD

**Issue by jannainm** [plaid/plaid-python#116]
In client.py the suppress_warnings flag returns a warning `...Swap out url for https://api.plaid.com...` if not set to True upon client initialization. After reviewing the code it seems this flag must be set to True in order to use the development environment. However, I don't see it mentioned anywhere else in the code. 

Perhaps this flag could be named something more indicative of its purpose. I am not clear if I am actually suppressing warnings the api would have returned otherwise. Also, the url contained in the warning message is a bit unclear. I believe the urls follow an https://environment.plaid.com scheme, so I am not sure why it mentions swapping out the url for https://api.plaid.com.

I may be missing something so if anyone can provide clarification on this or point me to any documentation where it is mentioned I will close the issue. Thanks for all your work on the client.

**Comment by joyzheng** [comment]
Thanks for reporting -- good catch, we should swap out `api.plaid.com` for `production.plaid.com` in that warning string. Unfortunately I think we're stuck with the naming for the sake of backwards compatibility, but we can definitely brush up the docstring to better explain what it does.

re: setting the flag to `True` in order to use the development environment, mind elaborating on what error you're seeing when the flag is set to `False`? My understanding is that it should print out a warning in this case, but shouldn't otherwise block you from using the library.

**Comment by jannainm** [comment]
@joyzheng thanks for the quick response. I just tested and the behavior matches your explanation. The warning does not stop my client from running. Perhaps I was lacking sleep that day. Submitted PR #117 to update the url. Closing this issue.
