### ISSUE TITLE
AttributeError: module 'plaid' has no attribute 'Client'

### ISSUE THREAD

**Issue by spider-hand** [plaid/plaid-python#120]
Hi, I'm trying to embed your quick start code into my program. This error

```
  client = plaid.Client(client_id = PLAID_CLIENT_ID, secret=PLAID_SECRET,
AttributeError: module 'plaid' has no attribute 'Client'
```

 happens when I combined your code into my program even though I run the quick start code successfully. I actually just copied the whole program. How can I fix this error?

**Comment by joyzheng** [comment]
Curious, thanks for reporting. Can you please let me know which version of `plaid-python` you currently have installed?

**Comment by spider-hand** [comment]
plaid==0.1.7
plaid-python==2.0.3

**Comment by joyzheng** [comment]
Ah, I'm guessing the issue may be that `plaid` is installed and when you go to import the package, the import is resolving to `plaid` instead of `plaid-python`?

**Comment by spider-hand** [comment]
I uninstalled `plaid` and now there's only `plaid-python` but the same error is still happening.

**Comment by spider-hand** [comment]
Actually seems like I was making dumb mistake, sorry... I figured it out.
Seems like the problem is one of my file names in my program is plaid.py and that caused the error...
Now I fixed the error.

**Comment by joyzheng** [comment]
Gotcha, glad you figured it out!

**Comment by pwaldo2** [comment]
The problem here isn't just the filename. There's also a library called plaid, which appears in your requirements.txt. The Python Ansible role checker (plaid 0.1.7) is not the same as Plaid (plaid-python) and is not a dependency for Plaid (plaid-python). The plaid 0.1.7 library has no module Client, but plaid-python does. Obviously this namespace issue is confusing. I had this problem by accident on Heroku, but because of the way they cache the site packages I could not uninstall plaid that somehow I accidentally installed. I had to change the python version in my runtime.txt, remove plaid 0.1.7 from requirements.txt and push into Heroku again and change my runtime.txt back. Then it all worked as expected.

**Comment by fexlneb** [comment]
@pwaldo2 - I do not use Heroku. I'm trying to just run the server.py. How do I get "import plaid" to run "plaid-python" instead of "plaid"?

**Comment by Jastor11** [comment]
@fexlneb - I also had the same issue in my Django app due to first installing plaid and having the namespaces clash. My requirements.text file was correct, but I was getting the same import error listed above. 

Here was my fix:

1. Test that the plaid package is imported instead of plaid-python by navigating to the shell and following @joyzheng 's instructions.

```bash
>>> import plaid
>>> plaid.__version__
AttributeError: module 'plaid' has no attribute '__version__'
>>> plaid.Client
AttributeError: module 'plaid' has no attribute 'Client'
>>> plaid.__dict__
{'__doc__': None,
 '__loader__': <_frozen_importlib_external._NamespaceLoader at 0x7f3fb21f0903>,
 '__name__': 'plaid',
 '__package__': 'plaid',
 '__path__': _NamespacePath(['your_path_here/lib/python3.7/site-packages/plaid']),
 '__spec__': ModuleSpec(name='plaid', loader=None, origin='namespace', submodule_search_locations=_NamespacePath(['your_path_here/lib/python3.7/site-packages/plaid']))}
```

2. Next, follow the instructions at this stackoverflow [answer](https://stackoverflow.com/a/11250821/11168715) for uninstalling all packages using pip. I'm using Docker and including the `--user` tag.

```bash
pip freeze --user | xargs pip uninstall -y
```

3. Make sure that your requirements.txt file only has plaid-python and not plaid listed. Reinstall all your packages.

```bash
pip install -r requirements.txt --user
```

4. For a sanity check, head back into the shell and try the original test. Here's my output:

```bash
>>> import plaid
>>> plaid.__version__
'3.4.0'
```

From there on out, everything worked.

**Comment by fexlneb** [comment]
@Jastor11 - thanks. This corrected the problem but now I'm receiving the 'access_token' is not defined error.
