### ISSUE TITLE
Change log update

### ISSUE THREAD

**Issue by tomhamiltonstubber** [plaid/plaid-python#278]
Hi folks,

Please can you keep the change log up to date? There's nothing there for the new version and it's a pain to work out what's changed when you don't even tag the releases.

**Comment by samuelcolvin** [comment]
Hi @michaelckelly @gae123 @pbernasconi please you reply to this.

It would be great if you could endeavour to maintain a change log for this project.

No community maintained open source project would get away with abandoning the changelog, I find it very surprising that a company as high profile and well funded as @plaid let their client libraries drop the ball like this.

I can't imagine stripe making a mistake like this.

**Comment by skylarmb** [comment]
Hi there all, not sure what the issue is here. Our changelog is actively maintained with each release and every release should have an entry here: https://github.com/plaid/plaid-python/blob/master/CHANGELOG.md

Our beta release changelog can be found on the beta branch: https://github.com/plaid/plaid-python/blob/8.0.0-beta-releases/CHANGELOG.md

**Comment by samuelcolvin** [comment]
> Hi there all, not sure what the issue is here.

Hi there, thanks for asking:
1. This issue was created on the 23rd of November, 3 days after v7.2 was released to pypi, the changelog you reference wasn't updated to reference v7.2 until 5 days ago, nearly 2 months after the release. As a reminder, changelogs are generally useful when releases are made, not after.
2. This repo has releases, but the most recent is from 2018 for v2.3.3.
