### ISSUE TITLE
AttributeError: module 'plaid' has no attribute 'LinkTokenCreateRequestUser'

### ISSUE THREAD

**Issue by surabhigupta2029** [plaid/plaid-python#373]
Hello!

I am building a web app and using Flask as my backend to make the Plaid API calls.
But, I keep getting the attribute error when trying to use my create_link_token path.

I feel like something is wrong with my ports assigned for frontend and backend, however I am not sure.

![image](https://user-images.githubusercontent.com/51391574/136309982-db8a6e9a-ed1a-4410-8859-23a2c4d0ce3f.png)

![image](https://user-images.githubusercontent.com/51391574/136310262-bf122dcd-622b-48da-b856-51cacfa8ec56.png)

## Flask code ##
![image](https://user-images.githubusercontent.com/51391574/136310095-2f25ff16-eb62-4c0b-b41e-be87ee2ea3df.png)

## React code ##
![image](https://user-images.githubusercontent.com/51391574/136310147-3026b33e-59e7-4213-bae3-b0221dcd0363.png)

**Comment by phoenixy1** [comment]
@surabhigupta2029 I think the issue is in your Flask code -- are you still having trouble with this? If so, try using the example from the test suite:

https://github.com/plaid/plaid-python/blob/master/tests/integration/test_link_token.py

once you've gotten that working, you can tweak it for your use case. Let us know if this fixes it or if you're still having problems!
