### ISSUE TITLE
Invalid type of variable item_login 

### ISSUE THREAD

**Issue by dev-fairshares** [plaid/plaid-python#443]
- hey there could some one help me out with this. i was trying to access institution by id request using option include status through sandbox error pop of with this message 

![image](https://user-images.githubusercontent.com/105924251/198755421-1c2ebaaa-d3a2-4ab5-9156-377adc5895f0.png)

**Comment by phoenixy1** [comment]
@dev-fairshares thanks for reporting this. It looks like this is a bug in the API -- institution status data isn't available in Sandbox, and `item_logins` isn't supposed to be returned in Sandbox, but instead it is being returned as null, which is not defined as a valid value for it in the client library. I'll make sure we fix this for the next client library version.

In the meantime, as a workaround, don't use `include_status: true` when calling institutions endpoints in Sandbox, since it's not supported in Sandbox anyway. If you need to test this parameter, use Development or Production -- it should work as long as you don't use Sandbox.
