### ISSUE TITLE
call to `identify_verification_get` returning `ApiAttributeError` on `DocumentaryVerificationDocument`

### ISSUE THREAD

**Issue by br-follow** [plaid/plaid-python#452]
When we receive a webhook about an updated to an identity verification flow, we call the SDK's `identity_verification_get` method.

Doing so throws the following error:
```
ApiAttributeError
DocumentaryVerificationDocument has no attribute 'redacted_at' at ['received_data']['documentary_verification']['documents'][0]['redacted_at']
```

I can see the IDV results in the plaid dashboard, where a documentary verification was performed and failed on a number of fields. It looks like `redacted_at` is missing from the response.

**Comment by phoenixy1** [comment]
@br-follow just to clarify, the situation is that you ARE in fact receiving 'redacted_at' in the API response, but the client library is NOT expecting it -- is that correct?

**Comment by br-follow** [comment]
I've not entirely sure yet - I would be surprised if the SDK throws an error if it finds a new value. So I would assume that we are not receiving redacted yet.

**Comment by phoenixy1** [comment]
@br-follow thanks for following up! 

The SDK is not **supposed** to throw an error if it finds a new value, but due to a series of unfortunate events (I can go into the details if you want, but basically there was a configuration error in impacting how certain objects in the python SDK were generated) it is in fact throwing an error if it finds a new value.

We plan to release an updated version of the python SDK tomorrow that will fix this issue.

**Comment by br-follow** [comment]
Thank you for the quick turnaround!

**Comment by phoenixy1** [comment]
Fix has been released!

**Comment by br-follow** [comment]
I don't see a new version released on pypi.

**Comment by bitdivision** [comment]
@phoenixy1 Any plans to release this to pypi?

**Comment by phoenixy1** [comment]
...and it should be released to pypi now!
