### ISSUE TITLE
[ERROR] GenericCountryCode as a model does not exist, but required?

### ISSUE THREAD

**Issue by marksarkisbond** [plaid/plaid-python#535]
I keep getting the issue below after trying to hit [this endpoint](https://plaid.com/docs/api/products/monitor/#watchlist_screeningindividualcreate): 
```plaid.exceptions.ApiTypeError: Invalid type for variable 'country'. Required value type is GenericCountryCode and passed type was str at ['country']``` but am not able to find `GenericCountryCode` in the models. The only reference I find to it is [here](https://github.com/Zapgram/pilot-plaid-python/blob/trunk/docs/GenericCountryCode.md). 

The documentation states
[country](https://plaid.com/docs/api/products/monitor/#watchlist_screening-individual-create-request-search-terms-country)
**string
Valid, capitalized, two-letter ISO code representing the country of this object. Must be in ISO 3166-1 alpha-2 form.**

Any help with this?

**Comment by marksarkisbond** [comment]
Update: (shoutout Lu)

It seems this is available in a previous version but not the current version

https://github.com/plaid/plaid-python/blob/505101c1aa51e94b7db8b78a143d5be7aca01f02/plaid/model/generic_country_code.py

**Comment by phoenixy1** [comment]
@marksarkisbond So apparently what happened is that in version 23 we removed the `minLength` restriction on the GenericCountryCode schema object (Changelog entry here: https://github.com/plaid/plaid-python/blob/master/CHANGELOG.md#2020-09-14_15241) to work around a bug in the ruby client library generator. It turns out that this caused GenericCountryCode to no longer be treated as a separate class by the python generator and instead to be treated as just a string, making it a breaking change to the client library, but we didn't realize this and therefore did not properly mark it as a breaking change.  :-/ 

Can you make sure you are using the latest version of the client library on all surfaces and passing this field as a string? In the latest version of the client library it is a string (see https://github.com/plaid/plaid-python/blob/27.0.0/plaid/model/watchlist_screening_request_search_terms.py).

**Comment by phoenixy1** [comment]
I believe this issue is resolved; closing this out.
