### ISSUE TITLE
How to debug PlaidServerError

### ISSUE THREAD

**Issue by ksindi** [plaid/plaid-python#89]
Using version (1.3.0). I started getting the error `PlaidServerError: An unexpected error has occurred on our systems; we've been notified and are looking into it!` when running `plaid_client.exchange_token(public_token)`. I'm not sure what's the cause of this error and would appreciate any suggestions as to what's happening. We started seeing this last weekend.

**Comment by joyzheng** [comment]
@ksindi -- `PlaidServerErrors` are generally ephemeral errors on the Plaid server and may often be resolved by retrying the request. 

If you're seeing this error consistently when calling `plaid_client.exchange_token(public_token)`, can you please open a case via the [Plaid Dashboard](https://dashboard.plaid.com/support) so that we can investigate?

The [Plaid Help Center](https://support.plaid.com/customer/en/portal/topics/973215-error-code-resolution) section on error codes is also a great resource about how to handle various classes of errors.

**Comment by ksindi** [comment]
@joyzheng will do. thanks.
